var Lang={'success':'Успешно',
'error':'Ошибка',
'trafic_realydelland':'Вы уверены, что хотите удалить лендинг?',
'yes':'Да',
'No':'Нет',
'trafic_realyclone':'Клонируем лендинг?',
'trafic_noname':'Без названия',
'trafic_realysetdef':'Вы действительно хотите сделать лендинг по умолчанию?',
'trafic_realysetfor_all':'Вы действительно хотите сделать лендинг для всех?',
'trafic_realysetfor_all_cancel':'Вы дейстительно хотите отменить?',
'success_domain_connect':'Домен успешно подключен, сайты начнут открываться на нем в течении некоторго времени',
'a_ns_not_found':'Записи не обнаружены',
'doamin_is_not_connect':'Кажется настройки домена еще не вступили в силу или указаны не правильно. Проверьте правильность настроек, если все правильно - подождите 24 часа.',
'set_domain':'Введите адрес домена',
'trafic_set_landing_to_alllp':'Вы действительно хотите назначить этот домен ко всем лендингам?',
'trafic_import_lp2':'Импортировать лендинг',
'trafic_create_lp2':'Создать лендинг',
'trafic_create_lp3':'Создать страницу благодарности',
'loading':'Загружаем',
'settings_add_photo':'Добавить изображение',
'trafic_add_fon':'Добавить фон',
'lang_errorLoadFile':'Ошибка при загрузке файла!',
'trafic__realdelbg':'Удалить выбранный фон?',
'days':'[#count] {[#count]:count| день ; дня ; дней}',
'attention':'Внимание!',
'no':'Нет',
'domains_domain_notavalible':'Домен занят, введите другой',
'domains_domain_incorrect':'Домен введен не корректно, или доменная зона не поддерживается',
'domains_datevydachi':'Дата выдачи',
'domains_who_get':'Кем выдан',
'domasins_serianomer':'Серия и номер',
'domains_namerus':'Имя (по-русски)',
'domains_surnamerus':'Фамилия (по-русски)',
'domains_patronicrus':'Отчество (по-русски)',
'domains_innprivate':'ИНН частного лица',
'domains_postcode':'Почтовый индекс',
'domains_oblast':'Область (необязательно)',
'domains_citynasel':'Город / населённый пункт',
'domains_streetdomkv':'Улица, дом, квартира',
'domains_birthday':'Дата рождения',
'domains_geter':'Получатель',
'domains_phone':'Телефон',
'domains_phone_for_online':'Телефон для онлайн-операций',
'domains_fax':'Факс',
'domains_phone_number_sms':'Телефонный номер sms-безопасности',
'domains_fion_eng':'Ф.И.О. (по-английски)',
'statistics_conversion':'Конверсия',
'forms_is_delete_form':'Вы действительно хотите удалить форму?',
'socialcrm_need_chrome':'Плагин можно установить только на браузер Chrome',
'balance_rearly_delsystem':'Вы уверены, что хотите удалить систему «[#title]»?',
'balance_promocode_applyed':'Промокод применен.',
'timer_day':'дн',
'timer_hr':'час',
'timer_min':'мин',
'timer_sec':'сек',
'chat_start_speaker':'Хотите быть спикером на этом вебинаре?',
'chat_message_sended':'Сообщение отправлено',
'chat_rearly_send_paymes':'Вы уверены, что хотите отправить уведомление на оплату?',
'chat_really_call_to_action':'Вы уверены, что хотите отправить призыв к действию?',
'chat_deleting_user':'Удаление пользователя',
'chat_are_you_shure_for_del_user':'Вы уверены, что хотите выгнать этого пользователя из комнаты?',
'yes_delete':'Да, удалить!',
'chat_banimg_user':'Бан пользователя',
'chat_disbanimg_user':'Разблокировка пользователя',
'yes_ban':'Да, заблокировать!',
'chat_yes_disban':'Да, разблокировать!',
'chat_you_kiked_out':'Вас выгнали из комнаты!',
'chat_is_baned':'Чат заблокирован',
'chat_you_was_baned':'Вас заблокировали!',
'chat_you_cant_write':'Вы больше не можете писать в чат!',
'chat_dont_flood_please':'Не флудите пожалуйста!',
'chat_rearly_clear_chat':'Очистить чат?',
'chat_lateenter':'Приходите в следующий раз, и не опаздывайте более чем на 5 минут!',
'links_realydel':'Вы уверены, что хотите удалить ссылку?',
'links_noname':'Без названия',
'saved':'Сохранено',
'chat_geting_pass_for_vebinar':'Получаем пароль на вебинар...',
'chat_pass_for_webinar':'Пароль от вебинара: [#pass]',
'chat_rearly_send_fkmes':'Вы уверены, что хотите запустить эмитацию пользовательской актиности?',
'chat_is_off':'Чат выключен',
'team_verify_confirme':'Вы действительно хотите верифицировать пользователя?',
'team_verify_rejecte':'Вы действительно хотите отклонить заявку?',
'sucess':'успешно',
'balance_do_send_balance':'Вы действительно хотите отправить средства?',
'balance_success_sendbalance':'Вы успешно перевели средства!',
'team_change_sponsor':'Изменить куратора',
'tema_realy_change_sponsor':'Вы действительно хотите изменить спонсора?',
'team_change_sponsor_desc':'Изменения коснуться всех партнеров данного пользователя',
'team_success_change_sponsor':'Вы успешно изменили спонсора!',
'set_delaycode_empty':'Укажите проверочный код из письма',
'settings_generel_team_access_saved':'Вы успешно обновили уровень доступа.',
'nitice_message_sended':'Сообщение успешно отправлено',
'events_ymap_search':'поиск...',
'events_enter_to_vebinar':'Войти на вебинар',
'events_allready_zap':'Вы записаны',
'events_suc_reg_webinar':'Вы успешно зарегистированы',
'save':'Сохранить',
'widget_stopvidto_end':'До конца видео осталось:',
'widget_hours':'[#cnt] {[#cnt]: count | час; часа; часа}',
'widget_minutes':'[#cnt] {[#cnt]: count | минута; минуты; минут}',
'widget_seconds':'[#cnt] {[#cnt]: count | секунда; секунды; секунд}',
'pages_access_denied':'Доступ запрещен',
'pages_access_prev_current':'Обучение происходит по шагам, сначала изучите материал на этой странице.',
'pages_access_to_group':'Страница доступна для пользователей из группы не ниже:',
'pages_access_prev_first':'Обучение происходит по шагам, сначала изучите предыдущий материал.',
'account_verify_del_quest':'Вы действительно хотите удалить эту верификацию?',
'account_change_photo':'Изменить фото',
'account_total':'Всего',
'account_messages_delall_ask':'Удаление переписки',
'account_messages_delall_text':'Вы уверены, что хотите удалить всю переписку?',
'account_maincities':'Основные города',
'account_regions':'Регионы',
'account_uploading':'Загружаем',
'account_sponsor_was_found':'Спонсор найден! Можно регистрироваться',
'account_sponsor_not_found':'Спонсор не найден',
'account_sponsor_search_again':'Есть идеи по каким данным еще поискать?',
'account_sponsor_ok_go_reg':'Тогда регистрируйтесь без спонсора, попробуем найти его позже',
'settings_balance_remove_period':'Удалить период?',
'settings_generel_accgroups_saved':'Вы успешно обновили список уровней доступа.',
'settings_success_domain_connect':'Домен успешно подключен, сайт начнeт открываться на нем в течении некоторго времени',
'a_ns_not_found_a':'Запись [#value] не обнаружена',
'domain_is_bad':'Указан не правильный домен или доменная зона не поддерживается.',
'settings_generel_menu_saved':'Успешно',
'settings_generel_menu_saved_text':'Настройки меню успешно сохранены, изменения вступят в силу после обновления страницы.',
'settings_general_new_menu':'Новый раздел',
'settings_add_moder_success':'Модератор добавлен',
'settings_add_moder_failed':'Произошла ошибка при добавлении модератора.',
'settings_enter_moder_name_and_select':'Введите часть имени или E-mail-а пользователя и выберите его из списка.',
'setting_user_will_not_be_a_moder':'Пользователь перестанет быть модератором.',
'settings_cancel':'Отмена',
'settings_remove_moder_success':'Модератор удален',
'settings_remove_moder_failed':'Произошла ошибка при удалении модератора.',
'svernut':'Свернуть',
'settigns_show_all_statuses_mainpage':'Показать настройки главных страниц для всех уровней доступа',
'affiliate_realy_want_decline':'Вы действительно хотите отклонить вывод средств?',
'settings_set_roylty_payment':'Укажите способ вывода средств',
'affiliate_realy_want_accept':'ВЫ ПОДТВЕРЖДАЕТЕ ВЫВОД СРЕДСТВ ПОЛЬЗОВАТЕЛЮ?',
'balance_realy_want_accept':'ВЫ ПОДТВЕРЖДАЕТЕ ВЫВОД СРЕДСТВ ПОЛЬЗОВАТЕЛЮ?',
'settings_change_slide_img':'Сменить изображение',
'widgets_real_del_slider':'Вы действительно хотите удалить слайдер?',
'widgets_real_Deletestopvid':'Вы действительно хотите удалить стоп-видео?',
'deposit_realy_want_decline':'Вы действительно хотите отклонить вывод депозита?',
'deposit_realy_want_accept':'ВЫ ПОДТВЕРЖДАЕТЕ ВЫВОД СРЕДСТВ ПОЛЬЗОВАТЕЛЮ?',
'settings__del_event':'Удалить событие?',
'settings__del_record':'Удалить запись?',
'settings__exp_record':'Создать страницу?',
'settings_incomeadv':'Заходы по рекламе',
'settings_total':'Всего',
'settings_bougth':'Купившие',
'settings_unbought':'Не купившие',
'settings_clickfordetails':'Кликните, чтобы увидеть детали',
'settings_dohodnostadv':'Доходность рекламных кампаний',
'settings_stat_salescnt':'Продаж',
'settings_stat_customers':'Клиентов',
'settings_buyers':'Покупок',
'settings_balance_remove_promo_code':'Удалить промокод?',
'settings_balance_delete':'Удалить',
'events_unfreeze':'Разморозить',
'events_freeze':'Заморозить',
'settings_are_you_sure':'Вы уверены?',
'set_delaycode_title':'Подтвердите ваше действие',
'leads_email_exists':'E-mail уже существует!',
'leads_enter_the_password_if_your_acc':'Такой аккаунт уже существует. Если это ваш аккаунт, для подтверждения введите пароль',
'leads_cancel':'Отмена',
'leads_password':'Введите пароль',
'leads_you_need_enter_the_pass':'Вы должны ввести верный пароль',
'landings_site_auth':'Авторизация на сайте',
'landings_saving':'Сохраняем...',
'landings_save':'Сохранить',
'landings_cantren_editormode':'Нельзя зарегистрироваться в режиме редактора',
'landings_copyed':'Скопировано!',
'landings_copy_buf':'Скопировать в буфер',
'landings_succcess_copy_buf':'Успешно скопировано в буфер обмена',
'leads_success':'Успешно!',
'landings_cant_auth_in_editor':'Нельзя зарегистрироваться в режиме редактора',
'landings_scrm_your_name':'Ваше имя',
'landings_scrm_your_phone':'Контактный телефон',
'landings_scrm_your_email':'Контактный E-mail',
'landings_scrm_noinads':'БЕЗ ВЛОЖЕНИЙ В РЕКЛАМУ',
'landings_scrm_noinsite':'БЕЗ ИНВЕСТИЦИЙ В САЙТ',
'landings_scrm_for_fewmminutes':'ЗА НЕСКОЛЬКО МИНУТ',
'landings_enter_skype':'Укажите пожалуйста ваш логин skype!',
'landings_enter_phone':'Укажите пожалуйста ваш номер телефона!',
'landings_success':'Успешно!',
}